name: Elixir deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test elixir code
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: ./.github/actions/test
  
  build_docker_image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-docker-image
        with:
          docker_repository: ${{ secrets.DOCKER_REPOSITORY }}
          docker_username: ${{ secrets.DOCKER_USERNAE }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}

  
  deploy: 
    name: Restart server
    needs: build_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server with ssh
        run: ssh ${{secrets.HOST_USERNAME}}:${{secrets.HOST_PASSWORD}}@${{secrets.HOST}}:${{secrets.HOST_PORT}}
        shell: bash
      - name: Cd to target dir
        run: cd /root/docker/my_desk
        shell: bash
      - name: Stop my desk server
        run: docker-compose stop my-desk-server 
        shell: bash
      - name: Restart my desk server
        run: docker-compose up -d --build my-desk-server
        shell: bash


