name: Elixir deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test elixir code
    steps:
      - uses: ./.github/actions/test.yml
  
  build_docker_image:
    name: Build and push docker image
    needs: test
    steps: 
      - uses: ./.github/actions/build-docker-image.yml
  
  deploy: 
    name: Restart server
    needs: build_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with ssh
        uses: applyboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            echo "deploy"

